<?php

namespace PackBot;

class HttpDescription
{
    public static array $codesDescriptionsRU = [
        0   => 'Нет ответа от сервера. Чаще всего это означает таймаут — сервер не ответил в отведённое время. Также может означать, что домен не существует, DNS не резолвится, или соединение было сброшено.',
        100 => 'Продолжайте. Сервер получил заголовки запроса и ожидает тело запроса от клиента.',
        101 => 'Переключение протоколов. Сервер переключается на протокол, указанный в заголовке Upgrade (например, на WebSocket).',
        102 => 'Обработка. Сервер принял запрос и обрабатывает его, но ответ пока не готов. Используется для предотвращения таймаута на стороне клиента.',
        103 => 'Ранние подсказки. Сервер отправляет предварительные заголовки (например, Link), чтобы браузер мог начать предзагрузку ресурсов до получения основного ответа.',
        200 => 'OK. Запрос выполнен успешно.',
        201 => 'Создано. Запрос выполнен успешно, в результате создан новый ресурс.',
        202 => 'Принято. Запрос принят к обработке, но обработка ещё не завершена. Результат будет доступен позже.',
        203 => 'Неавторитетная информация. Запрос выполнен успешно, но метаданные ответа получены не от исходного сервера, а из локального кэша или прокси.',
        204 => 'Нет содержимого. Запрос выполнен успешно, но сервер намеренно не возвращает тело ответа. Часто используется для AJAX-запросов и API.',
        205 => 'Сбросить содержимое. Запрос выполнен, сервер просит клиент сбросить отображение документа (например, очистить форму).',
        206 => 'Частичное содержимое. Сервер вернул только часть ресурса в ответ на запрос с заголовком Range. Используется при докачке файлов и потоковом воспроизведении.',
        207 => 'Многостатусный ответ (WebDAV). Тело ответа содержит XML с несколькими кодами состояния для нескольких подзапросов.',
        208 => 'Уже сообщено (WebDAV). Элементы уже были перечислены в предыдущей части ответа и не включаются повторно.',
        226 => 'IM использовано. Сервер выполнил запрос и ответ является результатом применения одной или нескольких манипуляций к текущему состоянию ресурса.',
        300 => 'Множество вариантов. Запрошенный ресурс имеет несколько представлений (например, разные форматы или языки), и клиент должен выбрать одно из них.',
        301 => 'Перемещено навсегда. Ресурс перенесён на новый URL. Поисковые системы обновят свои индексы. Новый адрес указан в заголовке Location.',
        302 => 'Найдено (временный редирект). Ресурс временно доступен по другому URL. Поисковые системы не будут обновлять индексы.',
        303 => 'Смотреть другое. Сервер перенаправляет клиента на другой URL с использованием метода GET. Часто используется после отправки формы.',
        304 => 'Не изменялось. Ресурс не менялся с момента последнего запроса. Браузер может использовать кэшированную версию.',
        305 => 'Использовать прокси. Доступ к ресурсу возможен только через прокси, указанный в ответе. Устаревший код.',
        306 => 'Зарезервировано. Этот код больше не используется, но зарезервирован для будущих целей.',
        307 => 'Временное перенаправление. Аналогичен 302, но гарантирует сохранение метода запроса (POST останется POST).',
        308 => 'Постоянное перенаправление. Аналогичен 301, но гарантирует сохранение метода запроса (POST останется POST).',
        400 => 'Неверный запрос. Сервер не смог обработать запрос из-за синтаксической ошибки. Проверьте правильность URL и параметров.',
        401 => 'Не авторизован. Для доступа к ресурсу требуется аутентификация (логин и пароль).',
        402 => 'Требуется оплата. Код зарезервирован для будущего использования в платёжных системах.',
        403 => 'Доступ запрещён. Сервер понял запрос, но отказывается его выполнять. Вероятно, Cloudflare или другая защита блокирует запрос. Если сайт принадлежит вам, добавьте useragent "PackBot/2.0 (+https://t.me/packhelperbot)" или IP-адрес "95.215.205.40" в белый список.',
        404 => 'Не найдено. Запрошенная страница или ресурс не существует на сервере.',
        405 => 'Метод не разрешён. Сервер знает этот HTTP-метод, но он запрещён для данного ресурса. Например, попытка отправить POST на ресурс, принимающий только GET.',
        406 => 'Неприемлемо. Сервер не может вернуть ответ в формате, который клиент готов принять (указанном в заголовках Accept).',
        407 => 'Требуется аутентификация прокси. Необходимо авторизоваться на прокси-сервере перед выполнением запроса.',
        408 => 'Таймаут запроса. Сервер не получил полный запрос от клиента за отведённое время. Попробуйте повторить запрос.',
        409 => 'Конфликт. Запрос конфликтует с текущим состоянием ресурса. Например, попытка создать ресурс, который уже существует.',
        410 => 'Удалено. Ресурс был намеренно и навсегда удалён с сервера. В отличие от 404, сервер знает, что ресурс существовал ранее.',
        411 => 'Требуется длина. Сервер отказывается обрабатывать запрос без заголовка Content-Length.',
        412 => 'Условие не выполнено. Одно из предусловий в заголовках запроса (If-Match, If-None-Match и т.д.) не выполнено.',
        413 => 'Слишком большое тело запроса. Размер данных запроса превышает лимит, установленный сервером.',
        414 => 'Слишком длинный URI. URL запроса превышает максимально допустимую длину. Обычно возникает при слишком большом количестве GET-параметров.',
        415 => 'Неподдерживаемый тип данных. Сервер не поддерживает формат данных в теле запроса. Например, отправлен XML, а сервер принимает только JSON.',
        416 => 'Недопустимый диапазон. Запрошенный диапазон данных (заголовок Range) выходит за пределы размера ресурса.',
        417 => 'Ожидание не оправдано. Сервер не может удовлетворить требование из заголовка Expect.',
        418 => 'Я — чайник. Шуточный код из протокола HTCPC. Сервер отказывается варить кофе, потому что является чайником.',
        421 => 'Неверно адресованный запрос. Запрос направлен на сервер, который не может его обработать. Может возникнуть при неправильной конфигурации мультидоменного хостинга.',
        422 => 'Необработанная сущность (WebDAV). Синтаксис запроса верен, но сервер не может его выполнить из-за семантических ошибок (например, невалидные данные формы).',
        423 => 'Заблокировано (WebDAV). Ресурс заблокирован и не может быть изменён.',
        424 => 'Сбой зависимости (WebDAV). Запрос не выполнен, потому что зависит от другого запроса, который завершился ошибкой.',
        425 => 'Слишком рано. Сервер не готов обрабатывать запрос, который может быть повторён (связано с TLS Early Data).',
        426 => 'Требуется обновление протокола. Сервер отказывается выполнять запрос по текущему протоколу, но готов сделать это после обновления (например, на TLS).',
        428 => 'Требуется предусловие. Сервер требует, чтобы запрос содержал условные заголовки (If-Match и т.д.) для предотвращения конфликтов.',
        429 => 'Слишком много запросов. Превышен лимит запросов. Сервер ограничивает частоту обращений. Повторите попытку позже.',
        431 => 'Слишком большие заголовки запроса. Размер одного или нескольких заголовков запроса превышает лимит сервера.',
        451 => 'Недоступно по юридическим причинам. Доступ к ресурсу заблокирован по требованию законодательства (например, DMCA, судебное решение, государственная цензура).',
        500 => 'Внутренняя ошибка сервера. На сервере произошла непредвиденная ошибка. Причины могут быть разные: ошибка в коде, проблемы с базой данных, неверная конфигурация. Нужно смотреть логи сервера.',
        501 => 'Не реализовано. Сервер не поддерживает функциональность, необходимую для выполнения запроса.',
        502 => 'Плохой шлюз. Сервер, работая как прокси или шлюз, получил некорректный ответ от вышестоящего сервера. Например, nginx не смог получить ответ от PHP-FPM или Apache.',
        503 => 'Сервис недоступен. Сервер временно не может обрабатывать запросы — перегрузка, обслуживание или перезапуск. Обычно проблема временная.',
        504 => 'Таймаут шлюза. Сервер, работая как прокси или шлюз, не дождался ответа от вышестоящего сервера. Скрипт или база данных работают слишком долго.',
        505 => 'Версия HTTP не поддерживается. Сервер не поддерживает версию протокола HTTP, указанную в запросе.',
        506 => 'Вариант тоже согласовывает. Внутренняя ошибка конфигурации: выбранный вариант ресурса сам указывает на необходимость согласования, создавая циклическую ссылку.',
        507 => 'Недостаточно места (WebDAV). На сервере закончилось место для сохранения данных, необходимых для выполнения запроса.',
        508 => 'Обнаружено зацикливание (WebDAV). Сервер обнаружил бесконечный цикл при обработке запроса.',
        510 => 'Не расширено. Для выполнения запроса требуются дополнительные расширения, которые сервер не поддерживает.',
        511 => 'Требуется сетевая аутентификация. Необходимо пройти аутентификацию для получения доступа к сети (например, авторизация в Wi-Fi портале).',
        526 => 'Ошибка SSL-сертификата. Скорее всего, SSL-сертификат на сервере недействителен, просрочен или неправильно настроен.',
    ];

    public static array $codesDescriptionsEN = [
        0   => 'No response from server. Most commonly this means a timeout — the server did not respond within the allotted time. It can also mean the domain does not exist, DNS failed to resolve, or the connection was reset.',
        100 => 'Continue. The server has received the request headers and the client should proceed to send the request body.',
        101 => 'Switching Protocols. The server is switching to the protocol specified in the Upgrade header (e.g., WebSocket).',
        102 => 'Processing (WebDAV). The server has accepted the request and is processing it, but no response is available yet.',
        103 => 'Early Hints. The server is sending preliminary headers (e.g., Link) so the browser can start preloading resources before the final response.',
        200 => 'OK. The request was successful.',
        201 => 'Created. The request was successful and a new resource was created as a result.',
        202 => 'Accepted. The request has been accepted for processing, but the processing has not been completed yet.',
        203 => 'Non-Authoritative Information. The request was successful, but the returned metadata is from a local or third-party copy, not the original server.',
        204 => 'No Content. The request was successful, but the server intentionally returns no body. Commonly used for AJAX requests and APIs.',
        205 => 'Reset Content. The request was successful, and the server asks the client to reset the document view (e.g., clear a form).',
        206 => 'Partial Content. The server is returning only part of the resource in response to a Range header. Used for resumable downloads and streaming.',
        207 => 'Multi-Status (WebDAV). The response body contains XML with multiple status codes for multiple sub-requests.',
        208 => 'Already Reported (WebDAV). The members have already been enumerated in a previous part of the response and are not included again.',
        226 => 'IM Used. The server has fulfilled the request, and the response is a representation of the result of instance-manipulations applied to the current instance.',
        300 => 'Multiple Choices. The requested resource has multiple representations (e.g., different formats or languages), and the client must choose one.',
        301 => 'Moved Permanently. The resource has been permanently moved to a new URL. Search engines will update their indexes. The new URL is provided in the Location header.',
        302 => 'Found (Temporary Redirect). The resource is temporarily available at a different URL. Search engines will not update their indexes.',
        303 => 'See Other. The server redirects the client to a different URL using the GET method. Often used after form submissions.',
        304 => 'Not Modified. The resource has not changed since the last request. The browser can use its cached version.',
        305 => 'Use Proxy. The resource is only accessible through a proxy specified in the response. Deprecated.',
        306 => 'Reserved. This status code is no longer used but is reserved for future purposes.',
        307 => 'Temporary Redirect. Similar to 302, but guarantees the request method is preserved (POST remains POST).',
        308 => 'Permanent Redirect. Similar to 301, but guarantees the request method is preserved (POST remains POST).',
        400 => 'Bad Request. The server could not process the request due to a syntax error. Check the URL and parameters.',
        401 => 'Unauthorized. Authentication (login and password) is required to access this resource.',
        402 => 'Payment Required. This code is reserved for future use in payment systems.',
        403 => 'Forbidden. The server understood the request but refuses to fulfill it. Likely Cloudflare or another protection system is blocking the request. If this is your site, add the useragent "PackBot/2.0 (+https://t.me/packhelperbot)" or IP address "95.215.205.40" to your whitelist.',
        404 => 'Not Found. The requested page or resource does not exist on the server.',
        405 => 'Method Not Allowed. The server recognizes the HTTP method but it is not allowed for this resource. For example, sending POST to a resource that only accepts GET.',
        406 => 'Not Acceptable. The server cannot return a response in a format the client is willing to accept (specified in Accept headers).',
        407 => 'Proxy Authentication Required. The client must authenticate with the proxy server before the request can proceed.',
        408 => 'Request Timeout. The server did not receive a complete request from the client within the allotted time. Try again.',
        409 => 'Conflict. The request conflicts with the current state of the resource. For example, trying to create a resource that already exists.',
        410 => 'Gone. The resource has been intentionally and permanently removed from the server. Unlike 404, the server knows the resource existed before.',
        411 => 'Length Required. The server refuses to process the request without a Content-Length header.',
        412 => 'Precondition Failed. One of the preconditions in the request headers (If-Match, If-None-Match, etc.) was not met.',
        413 => 'Payload Too Large. The request body exceeds the size limit set by the server.',
        414 => 'URI Too Long. The request URL exceeds the maximum allowed length. Usually occurs with too many GET parameters.',
        415 => 'Unsupported Media Type. The server does not support the format of the request body. For example, XML was sent but the server only accepts JSON.',
        416 => 'Range Not Satisfiable. The requested data range (Range header) is outside the bounds of the resource.',
        417 => 'Expectation Failed. The server cannot meet the requirement specified in the Expect header.',
        418 => 'I\'m a teapot. A joke status code from the HTCPC protocol. The server refuses to brew coffee because it is a teapot.',
        421 => 'Misdirected Request. The request was directed at a server that cannot process it. Can occur with misconfigured multi-domain hosting.',
        422 => 'Unprocessable Entity (WebDAV). The request syntax is correct, but the server cannot process it due to semantic errors (e.g., invalid form data).',
        423 => 'Locked (WebDAV). The resource is locked and cannot be modified.',
        424 => 'Failed Dependency (WebDAV). The request failed because it depends on another request that also failed.',
        425 => 'Too Early. The server is not ready to process a request that might be replayed (related to TLS Early Data).',
        426 => 'Upgrade Required. The server refuses to perform the request using the current protocol but is willing to do so after a protocol upgrade (e.g., to TLS).',
        428 => 'Precondition Required. The server requires the request to include conditional headers (If-Match, etc.) to prevent conflicts.',
        429 => 'Too Many Requests. Rate limit exceeded. The server is throttling requests. Try again later.',
        431 => 'Request Header Fields Too Large. The size of one or more request headers exceeds the server\'s limit.',
        451 => 'Unavailable For Legal Reasons. Access to the resource is blocked due to legal requirements (e.g., DMCA, court order, government censorship).',
        500 => 'Internal Server Error. An unexpected error occurred on the server. Possible causes: code bug, database issue, misconfiguration. Server logs should be checked.',
        501 => 'Not Implemented. The server does not support the functionality required to fulfill the request.',
        502 => 'Bad Gateway. The server, acting as a proxy or gateway, received an invalid response from the upstream server. For example, nginx could not get a response from PHP-FPM or Apache.',
        503 => 'Service Unavailable. The server is temporarily unable to handle requests — overloaded, under maintenance, or restarting. Usually a temporary issue.',
        504 => 'Gateway Timeout. The server, acting as a proxy or gateway, did not receive a timely response from the upstream server. A script or database query is taking too long.',
        505 => 'HTTP Version Not Supported. The server does not support the HTTP protocol version used in the request.',
        506 => 'Variant Also Negotiates. Internal configuration error: the chosen variant itself points to content negotiation, creating a circular reference.',
        507 => 'Insufficient Storage (WebDAV). The server has run out of space to store the data needed to complete the request.',
        508 => 'Loop Detected (WebDAV). The server detected an infinite loop while processing the request.',
        510 => 'Not Extended. The request requires additional extensions that the server does not support.',
        511 => 'Network Authentication Required. Authentication is needed to gain network access (e.g., Wi-Fi captive portal login).',
        526 => 'SSL Certificate Error. The SSL certificate on the server is most likely invalid, expired, or misconfigured.',
    ];

    /**
     * Returns a string with a textual description of what this or that response code means.
     * @param string $lang Language code. Currently supported: en_US, ru_RU
     */
    public static function getCodeDescription(int $code, string $lang): string
    {
        switch ($lang) {
            case 'en_US':
                return self::$codesDescriptionsEN[$code] ?? 'Unknown code. Please, refer to https://en.wikipedia.org/wiki/List_of_HTTP_status_codes for more information.';
            case 'ru_RU':
                return self::$codesDescriptionsRU[$code] ?? 'Неизвестный код. Пожалуйста, обратитесь к https://ru.wikipedia.org/wiki/Список_кодов_состояния_HTTP для получения дополнительной информации.';
            default:
                return self::$codesDescriptionsEN[$code] ?? 'Unknown';
        }
    }
}